#!/usr/bin/env python3

import argparse

from gitsearch.git_search import execute_search


def main():
    parser = argparse.ArgumentParser(description='Search github.')
    parser.add_argument('--scope', help='Search in users', default='repositories', choices=['repositories', 'users'])
    parser.add_argument('-l', '--language', help='Specify the language to search for')
    parser.add_argument('-u', '--user', help='Specify the user to search for')
    parser.add_argument('--nameonly', help='Only search in the name', action='store_true', default=False)
    parser.add_argument('--descriptiononly', help='Only search in the name', action='store_true', default=False)
    config, query = parser.parse_known_args()
    execute_search(config, query)


if __name__ == "__main__":
    main()
